# Generated by Django 4.2.6 on 2023-10-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
